[project]
name = "ilps-service-audio-preprocessing"
version = "0.1.0"
description = "ðŸ”Š Ð¡ÐµÑ€Ð²Ð¸Ñ Ð¿Ñ€ÐµÐ´Ð¾Ð±Ñ€Ð°Ð±Ð¾Ñ‚ÐºÐ¸ Ð°ÑƒÐ´Ð¸Ð¾Ñ„Ð°Ð¹Ð»Ð¾Ð² Ð² Ð¸Ð½Ñ„Ñ€Ð°ÑÑ‚Ñ€ÑƒÐºÑ‚ÑƒÑ€Ðµ ILPS"
authors = [
    {name = "Oidaho",email = "76991612+Oidaho@users.noreply.github.com"},
    {name = "Ronin-D",email = "100284945+Ronin-D@users.noreply.github.com"}
]
license = {text = "LICENSE"}
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "pydantic (>=2.11.3,<3.0.0)",
    "fastapi (>=0.115.12,<0.116.0)",
    "uvicorn (>=0.34.2,<0.35.0)",
    "pydantic-settings (>=2.9.1,<3.0.0)",
    "python-multipart (>=0.0.20,<0.0.21)",
    "loguru (>=0.7.3,<0.8.0)",
    "librosa (>=0.11.0,<0.12.0)",
    "noisereduce (>=3.0.3,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.urls]
repository = "https://github.com/FEFU-ILPS/service-audio-preprocessing"
"Bug Tracker" = "https://github.com/FEFU-ILPS/service-audio-preprocessing/issues"